name: Process Images in PR

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.md'

jobs:
  process-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webp
          pip install requests pillow beautifulsoup4 markdown

      - name: Process Images
        run: |
          python .github/scripts/process_images.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "chore: optimize images and update references"
            git push
          fi 